endbreadkings/breadgood

- breadgood-server/README.md
> feature : [docs] 리드미 문서화

- docker-compose.blue.yml
> test (jira) : 연동 테스트

- breadgood_app/lib/main.dart
화면 전환 효과 제거한 커밋입니다.
resolved: #7
> bug: [design] 화면 전환 효과 제거

- .github/workflows/cicd_dev.yml
- breadgood-server/src/main/java/com/bside/breadgood/util/AppleClientSecretUtils.java
애플 로그인 키 파일 및 secret key 설정 변경하였습니다.
너무 간단해서 요약만으로 리뷰 요청 합니당 ㅎㅎ
> feature: [login] 애플 로그인 secretkey 변경

- breadgood_app/lib/config/routes.dart
- breadgood_app/lib/modules/further_info/further_info.dart
- breadgood_app/lib/utils/ui/bottomNavigation.dart
더보기 notion link 추가
더보기 notion link 로 이동하는 부분 추가했습니다.
뒤로 가기를 넣어야하나 고민했는데, figma 디자인 작업대로 뒤로 가기 없는 버전으로 작업했습니다.
> feature: [더보기] 더보기 notion link 추가

- breadgood_app/lib/modules/login/screens/login_webview.dart
- 로그인 웹뷰화면 진입 시 AppBar가 다른 페이지와 다르게 보입니다.
- 해당 스크린의 AppBar가 다른 곳에서 사용하는 공통 컴포넌트가 아니여서 공통 AppBar로 수정
- 프론트 작업자 간 공통 컴포넌트에 대해서 공유가 되지 않는다면 앞으로도 충분히 발생할 수 있을 것 같은 이슈입니다.
- 공통적으로 사용되는 컴포넌트들에 대한 문서가 필요해보입니다.
- 문서가 어렵다면, 최소한 프론트 작업자들 간의 노티는 있어야할 것 같아요!
> bug: [로그인] 로그인 웹뷰화면 진입 시 AppBar가 다른 페이지와 다른 이슈

- breadgood-server/src/main/java/com/bside/breadgood/common/exception/IllegalFileExtensionException.java
- breadgood-server/src/main/java/com/bside/breadgood/s3/application/S3Service.java
- breadgood-server/src/main/java/com/bside/breadgood/util/FileUtils.java
- breadgood_app/ios/Podfile.lock
- breadgood_app/lib/modules/register_review/register_review.dart
- breadgood_app/pubspec.lock
- breadgood_app/pubspec.yaml
빵집 등록 시 ios 에서 이미지 업로드하면 이미지 업로드가 되지 않음
빵집 등록 시 ios 에서 이미지 업로드하면 'heic' 확장자이므로 업로드가 되지 않아 'jpeg'으로 변환 후 업로드하도록 함.
발생할 수 있는 모든 확장자 경우를 포함해야하는 것이 아닌가 고민하고 있습니다 따라서 refactoring 이 필요할지 고민하고 있습니다.
> bug: [빵집등록] ios 사진 업로드 시 등록 불가 이슈

- breadgood-server/src/main/resources/static/css/bakery-list.css
- breadgood-server/src/main/resources/static/js/component/bakeryList.jsx
[디자인] 지역 필터 핸들바 디자인 수정
1. 핸들바 margin 및 padding값 수정
2. 핸들바 드래그 닫기 모션 적용 범위 수정
3. 지역 필터 활성화 시 body 스크롤 방지
간단한 css 디자인 수정사항도 pull request를 통해 리뷰를 해야할 지 고민됩니다..!
개인적으로 바로 머지해서 빨리 디자인팀에 피드백을 받는 편이 더 효율적이지 않은가 싶습니다!
다른 분들의 의견은 어떠하신가요?
> fix: 지역필터 핸들바 디자인 수정 및 스크롤 고정

- breadgood_app/lib/main.dart
- breadgood_app/lib/modules/signup/screens/bread_style.dart
회원가입 시 최애빵 스타일 선택하는 화면에서 디자인상 필요한 여백 추가
회원가입 시 최애빵 스타일 선택하는 화면에서 '중복 선택 불가' 문구 아래 18px 여백 추가
단순 디자인 수정입니다
> design: [최애빵스타일 선택 화면] 여백 추가

- breadgood_app/lib/modules/my_page/screens/my_bread_style_edit.dart
- breadgood_app/lib/modules/my_page/screens/my_info_edit.dart
- breadgood_app/lib/modules/my_page/screens/my_nickname_edit.dart
- breadgood_app/lib/modules/register_bakery/screens/select_bakery_category.dart
내 정보 수정 화면에서 폰트, 색깔 변경 및 버튼 그림자 제거, 버튼 크기 변경
- 폰트 적용
- 폰트 색깔 및 버튼 색깔 적용
- 버튼 그림자 제거
- 버튼 높이 56px 적용
단순 디자인 적용 건입니다.
> design: [내정보수정] 폰트, 색깔 변경 빛 버튼 그림자 제거, 크기 변경

- breadgood_app/lib/modules/register_bakery/screens/select_bakery_category.dart
빵집 카테고리 선택화면 디자인 적용
- 폰트 적용
- 하단 버튼 여백 변경, elevation 제거, 그림자 적용
- 카테고리 선택 토글 버튼 그림자 적용, elevation 제거
디자인 적용건입니다
> design: [빵집 카테고리 선택 화면] 여백, 버튼 디자인, 폰트 수정

- breadgood-server/src/main/resources/static/js/component/bakeryList.jsx
- 빵집 리스트 카드의 'Pick' 빵스타일 배경색상으로 노출
- API에서 빵스타일 색상 코드를 제공해주어 빵 스타일 이름을 이용하여 분기처리하여 사용하던 로직을 제거하였습니다.
- none
> [빵집리스트] 'Pick' 빵스타일 배경색상으로 노출

- breadgood_app/lib/modules/my_page/screens/my_info_edit.dart
탈퇴 문구 수정 및 pop up 창 디자인 수정하였습니다.
탈퇴 문구 2번 수정하였고, pop up 창 radius 10으로 적용, padding 값 수정하였습니다.
없습니다
> [UVNX-156] 탈퇴 문구 수정

- breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/application/BakeryService.java
- breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/domain/Bakery.java
- breadgood-server/src/main/resources/static/css/bakery-list.css
- breadgood-server/src/main/resources/static/js/component/bakeryList.jsx
- breadgood-server/src/main/resources/templates/pages/bakeryDetail.html
- 빵집 리스트 카드 시그니처메뉴 & 리뷰 말줄임표
- 시그니처 메뉴10자 초과 시, 10자까지만 표현
- 리뷰 내용 23자 초과 시, 23자까지만 표현
- ❌
> [빵집 리스트] 빵집 카드의 시그니처 메뉴와 리뷰 말줄임표(...) 처리

- breadgood_app/lib/modules/register_bakery/screens/search_bakery.dart
- breadgood_app/pubspec.lock
빵집 검색결과 없을 시 회색고양이 나오지 않는 문제 해결
1. 빵집 검색결과 없을 시 회색 고양이 나오도록 수정
2. 문구 추가
3. textfield 활성화 시 primary Color 적용
가게명 일부만 입력 시 검색이 되지 않는 경우가 있는데 이에 대해 더 알아봐야할 것 같습니다
> [빵집 등록] 검색결과 없을 시 화면 설정 및 문구 추가

- breadgood_app/ios/Podfile.lock
- breadgood_app/ios/Runner.xcodeproj/project.pbxproj
- breadgood_app/lib/modules/register_bakery/model/bakery_category.dart
- breadgood_app/lib/modules/register_bakery/screens/select_bakery_category.dart
- breadgood_app/pubspec.lock
빵집 카테고리 이미지 로드 이슈 해결
BakeryCategoryResponseDto 의 멤버 중 하나인 "makerImgUrl"이 "markerImgUrl"로 naming 이 바뀌어서 생긴 오류로, 
BakeryCategoryResponseDto member naming 및 member 추가/삭제
언제부터 잘못됐는지 모르겠네요..
> [UVNX-211][빵집등록] 빵집 카테고리 이미지 로드 이슈

- breadgood_app/ios/Podfile.lock
- breadgood_app/ios/Runner.xcodeproj/project.pbxproj
- breadgood_app/lib/modules/further_info/further_info.dart
- breadgood_app/pubspec.lock
더보기 링크 변경
더보기 링크 변경 하드코딩 하였습니다.
단순 하드코딩 변경입니다.
> [UVNX-209][더보기] 더보기 링크 변경

- breadgood_app/lib/modules/signup/controller/signup_controller.dart
- breadgood_app/lib/modules/signup/screens/nick_name.dart
- breadgood_app/lib/utils/common/debounce.dart
- 회원가입 > 별명 입력 글자수 제한
- debounce 객체 생성
> UVNX-21 [회원가입]별명입력시 글자수 제한

- breadgood_app/lib/modules/register_bakery/screens/search_bakery.dart
* 빵집 검색 결과 카드 여백 조정
* 현재 가변 처리를 MediaQuery 이용해서 수정하였지만 Flexible, Expanded 가변 코드 리팩토링 필요할거 같아요🤔
> UVNX-160 [디자인]빵집 검색 결과 내 카드 디자인 수정

- breadgood_app/asset/images/icon/registerReview/register_review_info.svg
- breadgood_app/lib/modules/register_review/screens/register_review.dart
- breadgood_app/lib/utils/ui/colors.dart
* 리뷰 등록 > 최초 등록자, 추가 등록자에 따라 안내 문구 노출
* bakery == -1 조건으로 처리하면 되는지 확인 부탁드려요🙂 @kyeonghyeon 님!
* 공통으로 사용해야 할 컬러명도 고민입니당!
> UVNX-165 [디자인]리뷰등록_필수값미입력시 안내문구 추가

- breadgood-server/src/main/java/com/bside/breadgood/ddd/emoji/application/EmojiService.java
- breadgood-server/src/main/java/com/bside/breadgood/ddd/emoji/application/dto/EmojiResponseDto.java
- breadgood-server/src/main/java/com/bside/breadgood/ddd/emoji/domain/Emoji.java
- breadgood-server/src/main/java/com/bside/breadgood/ddd/emoji/infra/EmojiRepository.java
- breadgood-server/src/main/java/com/bside/breadgood/ddd/emoji/infra/InitEmojiData.java
- breadgood-server/src/main/java/com/bside/breadgood/ddd/emoji/ui/EmojiAdminController.java
- breadgood-server/src/test/java/com/bside/breadgood/ddd/bakery/application/BakeryServiceTest.java
- breadgood-server/src/test/java/com/bside/breadgood/ddd/bakery/domain/BakeryTest.java
- breadgood-server/src/test/java/com/bside/breadgood/ddd/emoji/infra/EmojiRepositoryTest.java
- breadgood-server/src/test/java/com/bside/breadgood/ddd/emoji/ui/EmojiAdminAcceptanceTest.java
- breadgood-server/src/test/java/com/bside/breadgood/fixtures/emoji/EmojiFixture.java
- 관리자 이모지 조회 API 추가
- 관리자 이모지 조회용 컨트롤러 추가
- 이모지 레파지토리, 인수 테스트 코드 추가
- 작업 사항이 많지 않아 큰 고민은 없었습니다 !
> [UVNX-201] 관리자 이모지 조회 API

- breadgood-server/src/main/java/com/bside/breadgood/ddd/breadstyles/application/BreadStyleService.java
> fix: bug fix

- breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/application/dto/BakeryReviewResponseDto.java
- breadgood-server/src/main/resources/static/css/bakery.css
- breadgood-server/src/main/resources/templates/pages/bakeryDetail.html
관린자가 빵집 상세 화면에서 빵집 삭제 기능 추가하였습니다.
> feat (bakeryReview) : 리뷰 삭제 추가

- breadgood_app/lib/modules/register_bakery/controller/bakery_controller.dart
- breadgood_app/lib/modules/register_review/screens/register_review.dart
- 시그니처 메뉴에서 활성화, 비활성화 조건이 달성되지 않아서 수정
- 시그니처 메뉴 입력이 하나라도 없으면 비활성화 되도록 변경
- 불필요한 import 제거
- 다음 작업으로 register_review Widget 분리 작업 생각~
> UVNX-120 등록 조건 미달성 시 '완성'버튼 비활성화

- breadgood_app/lib/modules/my_page/controller/edit_nickname_controller.dart
- breadgood_app/lib/modules/my_page/screens/my_nickname_edit.dart
- 별명 입력시 글자수만 제한하면 될줄 알았는데, 생각보다 기능이 빠져 있는 부분이 있어서 코드 전체 작업이 되었습니다.
- 사용하지 않는 코드 제거
- 빠져있던 기능 추가
> UVNX-155 [my빵긋]별명입력시 글자수 제한

- breadgood_app/lib/modules/my_page/controller/edit_nickname_controller.dart
- breadgood_app/lib/modules/my_page/screens/my_nickname_edit.dart
- breadgood_app/lib/modules/signup/controller/signup_controller.dart
- breadgood_app/lib/modules/signup/screens/nick_name.dart
* 글자수 8자리 미만 제한
* 티켓에다가 동영상 첨부
> UVNX-217 my빵긋]별명입력시 글자수 제한 재확인

- breadgood_app/ios/Runner.xcodeproj/project.pbxproj
- breadgood_app/lib/modules/my_page/screens/my_info_edit.dart
- breadgood_app/lib/modules/signup/controller/signup_controller.dart
- breadgood_app/pubspec.lock
회원가입 후 홈화면 진입 시 bottom navigation 나오지 않는 이슈 해결
-회원가입 완료 시 bottom navigation 으로 가도록 경로 수정
-회원탈퇴/로그아웃 시 bottom navigation 에 남아있는 페이지 방문 기록 초기화하여 재접속 시 main 화면 나오도록 수정
탈퇴/로그아웃 시 관리해야하는 controller data 정리하여 처리해야할 것으로 보임
> [UVNX-215] 회원가입 후 홈화면 진입 시 bottom navigation 나오지 않음

- breadgood_app/lib/modules/register_bakery/screens/select_bakery_category.dart
* 최초 등록자 빵집 카테고리 설정 필수값, 미선택할 때 다음 버튼 비활성화 처리
> UVNX-118 최초등록자 빵집 카테고리 설정은 필수값 -> 미선택시 다음 버튼 비활성화

- breadgood_app/lib/config/routes.dart
- breadgood_app/lib/main.dart
- breadgood_app/lib/modules/login/screens/login_webview.dart
- breadgood_app/lib/modules/signup/controller/signup_controller.dart
- breadgood_app/lib/utils/services/secure_storage_service.dart
- breadgood_app/test/widget_test.dart
* isLoggedIn 상태 추가 
* isLoggedIn 상태 따라서 로그인 또는 메인 페이지 이동
* 로그아웃 붙이고 나면 다시 확인 필요
* 주석으로 되어 있는 코드 제거 필요
* 불필요한 import 제거 필요
> isLoggedIn 상태 추가 및 초기 페이지 설정

- breadgood-server/src/main/java/com/bside/breadgood/InitDataEvent.java
- breadgood_app/ios/Podfile.lock
- breadgood_app/ios/Runner.xcodeproj/project.pbxproj
- breadgood_app/lib/modules/register_bakery/screens/search_bakery_card.dart
- breadgood_app/pubspec.lock
빵집 검색 결과 내 선택 버튼이 본래 디자인과 다르게 알약 모양으로 나오던 이슈 해결
Container 내 Flexible 때문에 영역 문제가 생겼던 것으로 보임
Android, ios simulator 에서는 발생하지 않고 배포 시에만 나타나는 문제라 재현이 어려웠음
> [UVNX-217] 빵집 검색 결과 내 선택 버튼 수정

- breadgood-server/src/main/java/com/bside/breadgood/InitDataEvent.java
- breadgood_app/ios/Podfile.lock
- breadgood_app/lib/constant/api_path.dart
- breadgood_app/lib/manager/dio_manager.dart
- breadgood_app/lib/modules/my_page/controller/edit_nickname_controller.dart
- breadgood_app/lib/modules/my_page/model/userinfo.dart
- breadgood_app/lib/modules/my_page/screens/my_bread_style_edit.dart
- breadgood_app/lib/modules/my_page/screens/my_info_edit.dart
- breadgood_app/lib/modules/register_bakery/controller/bakery_controller.dart
- breadgood_app/lib/modules/register_bakery/naver_search.dart
- breadgood_app/lib/modules/register_bakery/screens/already_registered_bakery.dart
- breadgood_app/pubspec.lock
개발서버명 변경
api.breadgood.com -> dev-api.breadgood.com
> [UVNX-219] 개발서버명 변경

- breadgood_app/lib/constant/api_path.dart
- breadgood_app/lib/modules/my_page/controller/edit_nickname_controller.dart
- breadgood_app/lib/modules/my_page/model/userinfo.dart
- breadgood_app/lib/modules/my_page/screens/my_bread_style_edit.dart
- breadgood_app/lib/modules/my_page/screens/my_info_edit.dart
- breadgood_app/lib/modules/register_bakery/controller/bakery_controller.dart
- breadgood_app/lib/modules/register_bakery/naver_search.dart
- breadgood_app/lib/modules/register_bakery/screens/already_registered_bakery.dart
url 변수에 https 가 빠져있어서 포함
실수로 https 를 빠뜨려서 추가합니다.
> [UVNX-220] fix: 변수에 https 포함
